# Generated by Django 5.2 on 2025-10-18 10:55

from django.db import migrations

def create_default_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    default_group = ['admin', 'customer', 'owner']

    for group_name in default_group:
        Group.objects.get_or_create(name=group_name)




class Migration(migrations.Migration):
    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_groups),
    ]
