# Generated by Django 5.2 on 2025-10-18 11:05
from django.contrib.auth.hashers import make_password
from django.db import migrations


def create_default_users(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Group = apps.get_model('auth', 'Group')

    # Only create user if it doesn't exist
    user, created = User.objects.get_or_create(
        username='appuser',
        defaults={
            'email': 'appuser@app.com',
            'first_name': 'appuser',
            'last_name': 'appuser',
            'is_active': True,
            'is_staff': True,
            'is_superuser': True,
            'password': make_password('app1122'),  # hash password
        }
    )

    # Assign admin group if it exists
    admin_group = Group.objects.filter(name='admin').first()
    if admin_group and user:
        user.groups.add(admin_group)


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('users', '0002_create_default_groups'),
    ]

    operations = [
        migrations.RunPython(create_default_users),
    ]
