# Generated by Django 5.2 on 2025-10-21 08:56

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderNumberGenerator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_id', models.CharField(max_length=60, unique=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_generated', models.BooleanField(default=False)),
                ('last_payment_date', models.DateField()),
                ('next_payment_date', models.DateField()),
                ('reference', models.CharField(max_length=60)),
                ('resultcode', models.CharField(max_length=60)),
                ('result', models.CharField(max_length=60)),
                ('message', models.CharField(max_length=60)),
                ('gateway_buyer_uuid', models.CharField(max_length=60)),
                ('payment_token', models.CharField(max_length=60)),
                ('qr', models.CharField(max_length=60)),
                ('payment_gateway_url', models.CharField(max_length=60)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='customers_orders', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('result', models.CharField(choices=[('SUCCESS', 'SUCCESS'), ('FAIL', 'FAIL')], max_length=20)),
                ('resultcode', models.CharField(max_length=20)),
                ('transid', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=50)),
                ('channel', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('phone', models.CharField(max_length=20)),
                ('payment_status', models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('CANCELLED', 'CANCELLED'), ('PENDING', 'PENDING'), ('USERCANCELED', 'USERCANCELED')], max_length=20)),
                ('orderid', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_payments', to='payment.customerorder')),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('type', models.CharField(choices=[('property owner', 'Property Owner'), ('broker', 'broker'), ('customer', 'Customer')], max_length=15)),
                ('interval', models.IntegerField(validators=[django.core.validators.MinValueValidator(30)])),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customerorder',
            name='fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='customer_fee', to='payment.fee'),
        ),
        migrations.CreateModel(
            name='OrderStaticConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('vendor_till', models.CharField(max_length=50)),
                ('remark', models.CharField(default='Payment For mobile application', max_length=50)),
                ('country', models.CharField(default='TZ', max_length=50)),
                ('city', models.CharField(default='Dar es salaam', max_length=50)),
                ('state_or_region', models.CharField(default='DA', max_length=50)),
                ('currency', models.CharField(choices=[('TZS', 'Tanzanian Shillings'), ('usd', 'US Dollar')], max_length=15)),
                ('payment_methods', models.CharField(choices=[('ALL', 'All'), ('MOBILEONLY', 'Mobile Only')], max_length=15)),
                ('no_of_items', models.PositiveIntegerField(default=1)),
                ('api_key', models.CharField(max_length=150)),
                ('secrets_key', models.CharField(max_length=150)),
                ('base_url', models.URLField()),
                ('webhook_url', models.URLField()),
                ('callback_url', models.URLField()),
                ('redirect_url', models.URLField()),
                ('cancel_url', models.URLField()),
                ('order_path', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='User who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customerorder',
            name='static_conf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conf_orders', to='payment.orderstaticconfig'),
        ),
    ]
